# Generated by Django 5.2.6 on 2025-09-30 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.mesa')),
            ],
        ),
    ]
