# Generated by Django 5.2.6 on 2025-11-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
