"""
Django settings for restaurante_project project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os

# ---------------------------------------------
# BASE DIR
# ---------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------
# SECURITY
# ---------------------------------------------
SECRET_KEY = 'django-insecure-a2=1ean2v_kv0z8f%aqa%86yk)=*bqhvvwh6kqv6_0rbg3)d^9'

DEBUG = True

ALLOWED_HOSTS = ["*"]  # ⚠️ Permite todo en desarrollo. Si quieres puedes cambiarlo luego.


# ---------------------------------------------
# INSTALLED APPS
# ---------------------------------------------
INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    'rest_framework',
    'corsheaders',

    # Apps propias
    'restaurante',
]


# ---------------------------------------------
# MIDDLEWARE
# ---------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 👈 Debe ir PRIMERO
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ---------------------------------------------
# URLS
# ---------------------------------------------
ROOT_URLCONF = 'restaurante_project.urls'


# ---------------------------------------------
# TEMPLATES
# ---------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # puedes agregar templates aquí si los usas
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ---------------------------------------------
# WSGI
# ---------------------------------------------
WSGI_APPLICATION = 'restaurante_project.wsgi.application'


# ---------------------------------------------
# DATABASE (SQLITE - TEMPORAL PARA DESARROLLO)
# ---------------------------------------------
# NOTA: Cambiar a PostgreSQL cuando se configure correctamente
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---------------------------------------------
# DATABASE (POSTGRESQL) - DESCOMENTAR CUANDO ESTÉ CONFIGURADO
# ---------------------------------------------
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'restaurante_db',
#         'USER': 'postgres',
#         'PASSWORD': 'laura1076502740',  # Cambiar por tu contraseña real
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# ---------------------------------------------
# VALIDACIÓN PASSWORD
# ---------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ---------------------------------------------
# INTERNACIONALIZACIÓN
# ---------------------------------------------
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'

USE_I18N = True
USE_TZ = True


# ---------------------------------------------
# STATIC FILES
# ---------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # útil en deploy

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# ---------------------------------------------
# DEFAULT PRIMARY KEY
# ---------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------
# CORS CONFIG → PERMITE ANGULAR
# ---------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
]

# Permite TODO en desarrollo
CORS_ALLOW_ALL_ORIGINS = True

# Permite envío de cookies desde Angular si algún día lo usas
CORS_ALLOW_CREDENTIALS = True
